<?php
	include_once("dfmodel.php");
	$con = new connection;
	$conn = $con->connect();
	$mod = new model;

	$allstatesel   = $mod->sel_record($conn,'state');
	$allprefix     = $mod->sel_record($conn,'PREFIX_MAST');
	$selallsp      = $mod->sel_record($conn,'SPECIALITY');
	$allopdtimings = $mod->sel_record($conn,'OPD_TIMINGS');		
//	var_dump($allstatesel);

	if (isset($_POST['Sign_In']))
	{
		$mycookie = "No";
		$msg      = "";
		$logintype = "";
		$myloginid = "";
		$mypswd    = "";
		$scities   = "";
		$arr = "";
		$j = 0;
	
		$_SESSION['loggedkey']      = "";	
		$_SESSION['logintype']      = "";		
		$_SESSION['prefix_cd']      = "";			
		$_SESSION['username']       = "";
		$_SESSION['loginid']        = "";
		$_SESSION['mobileno']       = "";
		$_SESSION['emailid']        = "";	
		$_SESSION['login_attempts'] = 0;

//		echo "inside Sign_in"."<br/>";
		$logintype = $_POST['logintype'];
//			echo "$logintype"."<br>" ;
		$myloginid = $_POST['myloginid'];	
//			echo "$myloginid"."<br>" ;
		$mypswd = $_POST['mypswd'];
//			echo "$mypswd"."<br>" ;
		if (isset($_POST['storecookie']))
		{
			$mycookie = $_REQUEST['storecookie'];
		}
		$status = "Active"; 
		if ($logintype == "User")
		{
			$data = array('ru_prefix_cd', 'ru_name', 'ru_login_id', 'ru_mobile', 'ru_email', 'ru_pswd');
			$where = array('ru_login_id'=>$myloginid, 'ru_mobile'=>$myloginid, 'ru_email'=>$myloginid);
			$pswdstr = array('ru_pswd'=>$mypswd);
			$appcond = array('ru_status'=>$status);
			$ex = $mod->login($conn, $data, 'reguser', $where, $pswdstr, $appcond);

/*			-- Following query is generated by calling above login function with the specified arguments for ru, rd & ra --

			$loginquery = "select ru_login_id, ru_mobile, ru_email, ru_pswd, ru_prefix_cd, ru_name 
							from reguser 			
							where ((ru_login_id = '$myloginid' and ru_pswd = '$mypswd') or
								   (ru_mobile = '$myloginid' and ru_pswd = '$mypswd') or
								   (ru_email = '$myloginid' and ru_pswd = '$mypswd')) and
								   ru_status = '$status')";
*/
		}
		else if ($logintype == "Dr. ")
		{
			$data = array('rd_prefix_cd', 'rd_name', 'rd_login_id', 'rd_mobile', 'rd_email', 'rd_pswd');
			$where = array('rd_login_id'=>$myloginid, 'rd_mobile'=>$myloginid, 'rd_email'=>$myloginid);
			$pswdstr = array('rd_pswd'=>$mypswd);
			$appcond = array('rd_status'=>$status);
			$ex = $mod->login($conn, $data, 'regdoctor', $where, $pswdstr, $appcond);
		}
		else if ($logintype == "Admin")
		{
			$data = array('ra_prefix_cd', 'ra_name', 'ra_login_id', 'ra_mobile', 'ra_email', 'ra_pswd');
			$where = array('ra_login_id'=>$myloginid, 'ra_mobile'=>$myloginid, 'ra_email'=>$myloginid);
			$pswdstr = array('ra_pswd'=>$mypswd);
			$appcond = array('ra_status'=>$status);
			$ex = $mod->login($conn, $data, 'regadmin', $where, $pswdstr, $appcond);
		}
		$res = $ex->fetch_object();
		if ($ex->num_rows > 0) 
		{
			if ($logintype == "User")
			{			
				$_SESSION['logintype'] = "User";
				$_SESSION['loggedkey'] = "yes";				
				$_SESSION['loginid']   = $res->ru_login_id;								
				$_SESSION['prefix_cd'] = $res->ru_prefix_cd;			
				$_SESSION['username']  = $res->ru_name;
				$_SESSION['mobileno']  = $res->ru_mobile;
				$_SESSION['emailid']   = $res->ru_email;
			}
			else if ($logintype == "Dr. ")
			{
				$_SESSION['logintype'] = "Dr. ";
				$_SESSION['loggedkey'] = "yes";						
				$_SESSION['loginid']   = $res->rd_login_id;															
				$_SESSION['prefix_cd'] = $res->rd_prefix_cd;			
				$_SESSION['username']  = $res->rd_name;
				$_SESSION['mobileno']  = $res->rd_mobile;
				$_SESSION['emailid']   = $res->rd_email;										
			}
			else if ($logintype == "Admin")
			{
				$_SESSION['logintype'] = "Admin";
				$_SESSION['loggedkey'] = "yes";					
				$_SESSION['loginid']   = $res->ra_login_id;			
				$_SESSION['prefix_cd'] = $res->ra_prefix_cd;			
				$_SESSION['username']  = $res->ra_name;
				$_SESSION['mobileno']  = $res->ra_mobile;
				$_SESSION['emailid']   = $res->ra_email;										
			}

			if ($mycookie == 'Yes')
			{
				setcookie('loginid', $_REQUEST['myloginid'], time()+36);
			}
		}
	}
//  for inserting a new User in a reguser table ... 	
	if (isset($_REQUEST['SAVE_USER_REG']))
	{
//		echo "inside dfcontroller ... SAVE_USER_REG";
		if (isset($_REQUEST['RU_PREFIX_CD']))
		{
			$ru_prefix_cd     = $_REQUEST['RU_PREFIX_CD'];		
		}
		$ru_name          = strtoupper(addslashes($_REQUEST['RU_NAME']));		
		$ru_gender        = addslashes($_REQUEST['RU_GENDER']);
		$ru_login_id      = addslashes($_REQUEST['RU_LOGIN_ID']);
		$ru_pswd          = addslashes($_REQUEST['RU_PSWD']);
		$ru_email         = addslashes($_REQUEST['RU_EMAIL']);
		$ru_mobile        = addslashes($_REQUEST['RU_MOBILE']);								
		$ru_ll_phone      = addslashes($_REQUEST['RU_LL_PHONE']);
		$ru_address       = strtoupper(addslashes($_REQUEST['RU_ADDRESS']));
		if (isset($_REQUEST['RU_LOC_CD']))
		{
			$ru_loc_cd        = $_REQUEST['RU_LOC_CD'];	
		}
		$ru_status        = "ACTIVE";														

		$seluser = "select * from reguser where RU_NAME = '$ru_name'";

//		echo $seluser;
//		die;		
		$ex = $conn->query($seluser);
		$res = $ex->fetch_object();
	}

//  for inserting a new Admin in a regadmin table ... 	
	if (isset($_REQUEST['SAVE_ADMIN_REG']))
	{
//		echo "inside dfcontroller ... SAVE_ADMIN_REG";
		if (isset($_REQUEST['RA_PREFIX_CD']))
		{
			$ra_prefix_cd     = $_REQUEST['RA_PREFIX_CD'];		
		}
		$ra_name          = strtoupper(addslashes($_REQUEST['RA_NAME']));		
		$ra_gender        = addslashes($_REQUEST['RA_GENDER']);
		$ra_login_id      = addslashes($_REQUEST['RA_LOGIN_ID']);
		$ra_pswd          = addslashes($_REQUEST['RA_PSWD']);
		$ra_email         = addslashes($_REQUEST['RA_EMAIL']);
		$ra_mobile        = addslashes($_REQUEST['RA_MOBILE']);								
		$ra_ll_phone      = addslashes($_REQUEST['RA_LL_PHONE']);
		$ra_address       = strtoupper(addslashes($_REQUEST['RA_ADDRESS']));
		if (isset($_REQUEST['RA_LOC_CD']))
		{
			$ra_loc_cd        = $_REQUEST['RA_LOC_CD'];	
		}
		$ra_status        = "ACTIVE";														

		$seladmin = "select * from regadmin where RA_NAME = '$ra_name'";

//		echo $seladmin;
//		die;		
		$ex = $conn->query($seladmin);
		$res = $ex->fetch_object();
	}

//  for inserting a new Doctor in a regdoctor table ... 	
	if (isset($_REQUEST['SAVE_DOCT_REG']))
	{
//		echo "inside dfcontroller ... SAVE_DOCT_REG";
		if (isset($_REQUEST['RD_PREFIX_CD']))
		{
			$rd_prefix_cd     = $_REQUEST['RD_PREFIX_CD'];		
		}	
		$rd_name           = strtoupper(addslashes($_REQUEST['RD_NAME']));		
		$rd_gender         = addslashes($_REQUEST['RD_GENDER']);
		$rd_quali          = strtoupper(addslashes($_REQUEST['RD_QUALI']));
		$rd_sp_cd          = addslashes($_REQUEST['RD_SP_CD']);
		$rd_mrno           = strtoupper(addslashes($_REQUEST['RD_MRNO']));				
		$rd_login_id       = addslashes($_REQUEST['RD_LOGIN_ID']);
		$rd_pswd           = addslashes($_REQUEST['RD_PSWD']);
		$rd_mobile         = addslashes($_REQUEST['RD_MOBILE']);		
		$rd_email          = addslashes($_REQUEST['RD_EMAIL']);
		$rd_clinic_ll      = addslashes($_REQUEST['RD_CLINIC_LL']);
		$rd_clinic_address = strtoupper(addslashes($_REQUEST['RD_CLINIC_ADDRESS']));
		$rd_resid_ll       = addslashes($_REQUEST['RD_RESID_LL']);
		$rd_resid_address  = strtoupper(addslashes($_REQUEST['RD_RESID_ADDRESS']));
		$rd_charge_i       = addslashes($_REQUEST['RD_CHARGE_I']);
		$rd_charge_ii      = addslashes($_REQUEST['RD_CHARGE_II']);
		$rd_mopd_from      = addslashes($_REQUEST['RD_MOPD_FROM']);
		$rd_mopd_to        = addslashes($_REQUEST['RD_MOPD_TO']);
		$rd_eopd_from      = addslashes($_REQUEST['RD_EOPD_FROM']);
		$rd_eopd_to        = addslashes($_REQUEST['RD_EOPD_TO']);						
		$rd_app_slot       = addslashes($_REQUEST['RD_APP_SLOT']);						
		if (isset($_REQUEST['RD_LOC_CD']))
		{
			$rd_loc_cd        = $_REQUEST['RD_LOC_CD'];	
		}		
		$rd_status         = "ACTIVE";														

		$seldoct = "select * from regdoctor where RD_NAME = '$rd_name'";

//		echo $seldoct;
//		die;		
		$ex = $conn->query($seldoct);
		$res = $ex->fetch_object();
	}

//  for updating an existing User in a reguser table ... 	
	if (isset($_REQUEST['UPDATE_USER_REG']))
	{
//		echo "inside dfcontroller ... UPDATE_USER_REG";
		if (isset($_REQUEST['RU_PREFIX_CD']))
		{
			$ru_prefix_cd     = $_REQUEST['RU_PREFIX_CD'];		
		}
		$ru_name          = strtoupper(addslashes($_REQUEST['RU_NAME']));		
		$ru_gender        = addslashes($_REQUEST['RU_GENDER']);
		$ru_login_id      = addslashes($_REQUEST['RU_LOGIN_ID']);
		$ru_pswd          = addslashes($_REQUEST['RU_PSWD']);
		$ru_email         = addslashes($_REQUEST['RU_EMAIL']);
		$ru_mobile        = addslashes($_REQUEST['RU_MOBILE']);								
		$ru_ll_phone      = addslashes($_REQUEST['RU_LL_PHONE']);
		$ru_address       = strtoupper(addslashes($_REQUEST['RU_ADDRESS']));
		if (isset($_REQUEST['RU_LOC_CD']))
		{
			$ru_loc_cd        = $_REQUEST['RU_LOC_CD'];	
		}		
		$ru_status        = "ACTIVE";														
	}
	
//	for updating an existing Doctor in a regdoctor table ... 
	if (isset($_REQUEST['UPDATE_DOCT_REG']))
	{
//		echo "inside dfcontroller ... UPDATE_DOCT_REG";
		if (isset($_REQUEST['RD_PREFIX_CD']))
		{
			$rd_prefix_cd     = $_REQUEST['RD_PREFIX_CD'];		
		}
	
		$rd_name           = strtoupper(addslashes($_REQUEST['RD_NAME']));		
		$rd_gender         = addslashes($_REQUEST['RD_GENDER']);
		$rd_quali          = strtoupper(addslashes($_REQUEST['RD_QUALI']));
		$rd_sp_cd          = addslashes($_REQUEST['RD_SP_CD']);
		$rd_mrno           = strtoupper(addslashes($_REQUEST['RD_MRNO']));				
		$rd_login_id       = addslashes($_REQUEST['RD_LOGIN_ID']);
		$rd_pswd           = addslashes($_REQUEST['RD_PSWD']);
		$rd_mobile         = addslashes($_REQUEST['RD_MOBILE']);		
		$rd_email          = addslashes($_REQUEST['RD_EMAIL']);
		$rd_clinic_ll      = addslashes($_REQUEST['RD_CLINIC_LL']);
		$rd_clinic_address = strtoupper(addslashes($_REQUEST['RD_CLINIC_ADDRESS']));
		$rd_resid_ll       = addslashes($_REQUEST['RD_RESID_LL']);
		$rd_resid_address  = strtoupper(addslashes($_REQUEST['RD_RESID_ADDRESS']));
		$rd_charge_i       = addslashes($_REQUEST['RD_CHARGE_I']);
		$rd_charge_ii      = addslashes($_REQUEST['RD_CHARGE_II']);
		$rd_mopd_from      = addslashes($_REQUEST['RD_MOPD_FROM']);
		$rd_mopd_to        = addslashes($_REQUEST['RD_MOPD_TO']);
		$rd_eopd_from      = addslashes($_REQUEST['RD_EOPD_FROM']);
		$rd_eopd_to        = addslashes($_REQUEST['RD_EOPD_TO']);						
		$rd_app_slot       = addslashes($_REQUEST['RD_APP_SLOT']);						
		if (isset($_REQUEST['RD_LOC_CD']))
		{
			$rd_loc_cd        = $_REQUEST['RD_LOC_CD'];	
		}				
		$rd_status         = "ACTIVE";														
	}

//  for updating an existing Admin in a regadmin table ... 	
	if (isset($_REQUEST['UPDATE_ADMIN_REG']))
	{
//		echo "inside dfcontroller ... UPDATE_ADMIN_REG";
		if (isset($_REQUEST['RA_PREFIX_CD']))
		{
			$ra_prefix_cd     = $_REQUEST['RA_PREFIX_CD'];		
		}

		$ra_name          = strtoupper(addslashes($_REQUEST['RA_NAME']));		
		$ra_gender        = addslashes($_REQUEST['RA_GENDER']);
		$ra_login_id      = addslashes($_REQUEST['RA_LOGIN_ID']);
		$ra_pswd          = addslashes($_REQUEST['RA_PSWD']);
		$ra_email         = addslashes($_REQUEST['RA_EMAIL']);
		$ra_mobile        = addslashes($_REQUEST['RA_MOBILE']);								
		$ra_ll_phone      = addslashes($_REQUEST['RA_LL_PHONE']);
		$ra_address       = strtoupper(addslashes($_REQUEST['RA_ADDRESS']));
		if (isset($_REQUEST['RA_LOC_CD']))
		{
			$ra_loc_cd        = $_REQUEST['RA_LOC_CD'];	
		}
		$ra_status        = "ACTIVE";														
	}

//  for creating a row in DNA_SCHEDULE table for doctors non availability ... 	
	if (isset($_REQUEST['SAVE_DOCT_NAREG']))
	{
//		echo "inside dfcontroller ... SAVE_DOCT_NAREG";
		$dna_rd_id        = $_SESSION['loggedkey'];
		$var              = $_REQUEST['DNA_STDATE'];
		$dna_wk_srno      = date("W", strtotime($var));		
		$dna_stdate       = date("Y/m/d", strtotime($var));
		$var              = $_REQUEST['DNA_ENDATE'];
		$dna_endate       = date("Y/m/d", strtotime($var));
		$dna_me_code      = $_REQUEST['DNA_ME_CODE'];

		$seldoct_nareg = "select * from dna_schedule where DNA_RD_ID = '$dna_rd_id' and DNA_STDATE = '$dna_stdate' and DNA_ENDATE = '$dna_endate'";

//		echo $seldoct_nareg;
//		die;		
		$ex = $conn->query($seldoct_nareg);
		$res = $ex->fetch_object();
	}

//  for inserting a new State in a state table ... 	
	if (isset($_POST['SAVE_STATE']))
	{
//		echo "inside dfcontroller ... save_state";
		$state_name = strtoupper(addslashes($_REQUEST['state']));		
		$selstate = "select * from state where state_name = '$state_name'";
//		echo $selstate;
//		die;		
		$ex = $conn->query($selstate);
		$res = $ex->fetch_object();
	}

//  for inserting a new City in the city table under a selected state  ... 	
	if (isset($_POST['SAVE_CITY']))
	{
//		echo "inside dfcontroller ... save_city";
		if (isset($_REQUEST['state_code']))
		{
			$state_code = addslashes($_REQUEST['state_code']);
		}
		if (isset($_REQUEST['city_name']))
		{
			$city_name  = strtoupper(addslashes($_REQUEST['city_name']));		

		}
		$selcity    = "select * from city where city_name = '$city_name' and state_code = '$state_code'";
//		echo $selcity;
//		die;		
		$ex = $conn->query($selcity);
		$res = $ex->fetch_object();
	}	

//  for inserting a new Location in a location table under a selected state & city ... 	
	if (isset($_POST['SAVE_LOC']))
	{
//		echo "inside dfcontroller ... save_loc";
		if (isset($_REQUEST['STATE_CODE']))
		{
			$state_code = addslashes($_REQUEST['state_code']);
		}
		else
		{
			$state_code = "";
		}
		if (isset($_REQUEST['city_code']))
		{
			$city_code = addslashes($_REQUEST['city_code']);		
		}
		else
		{
			$city_code = "";
		}
		if (isset($_REQUEST['location']))
		{
			$location = strtoupper(addslashes($_REQUEST['location']));	
		}
		else
		{
			$location = "";
		}

		$data  = array('location');
		$table = 'LOCATION l';
		$jtable1 = 'CITY c';
		$jc1 = array('l.CITY_CODE', 'c.CITY_CODE');
		$jtable2 = 'STATE s';
		$jc2 = array('c.STATE_CODE', 's.STATE_CODE');
		$where = "c.CITY_CODE = '$city_code' and s.STATE_CODE = '$state_code' and l.LOCATION = '$location'";					

		$ex = $mod->jointable($conn, $data, $table, $jtable1, $jc1, $jtable2, $jc2, $where);
/*
		$selloc    = "select location from location l join city c on l.city_code = c.city_code
						join state s on c.state_code = s.state_code
						where c.city_code = $city_code and
						      s.state_code = $state_code and
						      l.location = '$location'"; 
		$ex = $conn->query($selloc);
*/
	}
	
//  for updating a state in a state table ... 
	if (isset($_REQUEST['supdate_state']))
	{
//		echo "inside dfcontroller ....."."<br>";
//		die;
		$state_code = $_REQUEST['state_code'];
		$edited_sname = strtoupper(addslashes($_REQUEST['state_name']));
		$selstate     = "select state_code, state_name from state where state_name = '$edited_sname'";
//		echo $selstate."<br>";
//		die;
		$ex = $conn->query($selstate);
	}

//  for updating a city in a city table ... 
	if (isset($_REQUEST['cupdate_city']))
	{
//		echo "inside dfcontroller ....."."<br>";
//		die;
		$city_code = $_REQUEST['city_code'];
		$edited_cname = strtoupper(addslashes($_REQUEST['city_name']));
		$selcity     = "select city_code, city_name from city where city_name = '$edited_cname'";
//		echo $selcity."<br>";
//		die;
		$ex = $conn->query($selcity);
	}

//  for updating a location in a location table ... 
	if (isset($_REQUEST['lupdate_loc']))
	{
//		echo "inside dfcontroller ....."."<br>";
//		die;
		$loc_code = $_REQUEST['loc_code'];
		$edited_location = strtoupper(addslashes($_REQUEST['location']));
		$selloc     = "select loc_code, location from location where location = '$edited_location'";
//		echo $selcity."<br>";
//		die;
		$ex = $conn->query($selloc);
	}

//  for deleting a state from state table ... 
	if (isset($_REQUEST['sdelete_state']))
	{
		$state_code = $_REQUEST['state_code'];
		$where = array('state_code'=>$state_code);
		$mod->delete($conn, 'state', $where);		
	}	

//  for deleting a city from city table ... 
	if (isset($_REQUEST['cdelete_city']))
	{
		$city_code = $_REQUEST['city_code'];
		$where = array('city_code'=>$city_code);
		$mod->delete($conn, 'city', $where);		
	}	

//  for deleting a location from location table ... 
	if (isset($_REQUEST['ldelete_loc']))
	{
		$loc_code = $_REQUEST['loc_code'];
		$where = array('loc_code'=>$loc_code);
		$mod->delete($conn, 'location', $where);		
	}	

//	for multiple deletes of state table ...
	if (isset($_REQUEST['mdelete_state']))
	{
//		echo "inside dfcontroller mdelete_state ....";
		if (isset($_REQUEST['state_cd']))
		{
			$arr_scode = $_REQUEST['state_cd'];		
		}
//		var_dump($arr_scode);
//		die;
		for ($j=0; $j < count($arr_scode); $j++)
		{
			$where = array('state_code'=>$arr_scode[$j]);
			$mod->delete($conn, 'state', $where);		
		}
	}
?>